### ISSUE TITLE
characteristic functions return 1/0 instead of True/False

### ISSUE THREAD

**Issue by EasyArray** [EasyArray/phosphorus#10]

**Comment by havijw** [comment]
This should be an easy fix. Just want to make sure I'm understanding `SetVal.__call__` correctly:
- When the set is represents a function, apply the function to the input and raise an error if the input isn't in the domain.
- If the set is almost a function but some inputs have multiple outputs, return a list of all the outputs for the given input, and raise an error if there are none.
  - This is main part I was a bit unsure about after looking at the code.
- Otherwise, treat the set as an indicator function, using 1/0 instead of True/False.

**Comment by EasyArray** [comment]
That is correct -- maybe this would be a good first task for you? For now:

- Document that function better as-is
- Change it to return 1/0 in that one case of being an "indicator" (/characteristic) function
- Test the pull request or branch mechanism

In the future, though, some of this logic will be removed from SetVal and instead used in the class for explicit functions.
