### ISSUE TITLE
lambda substitution should be in parens

### ISSUE THREAD

**Issue by EasyArray** [EasyArray/phosphorus#32]
For instance,
```
[λf . [λx . 5+f(x)]]([λx . x>2])
[λf . [λx . 5+f(x)]]([λx . x>2])(3)
[λf . [λx . 5+(f(x))]]([λx . x>2])
[λf . [λx . 5+(f(x))]]([λx . x>2])(3)
```
produces:
```
[λx∈e. 5+ x>2]
True
[λx∈e. 5+( x>2)]
6
```

**Comment by havijw** [comment]
I think the parens-wrapping should happen in `Span.update`, since I could imagine similar problems coming up, for example, in `run` for rules (where `update` is also called). Are there any potential downsides to doing this? I don't know all the places where `update` is called. (Regression testing might be able to answer this question but I don't know if past notebooks cover all the places `update` is used).

**Comment by havijw** [comment]
Just to clarify — the problem here is that the result of a &beta;-reduction (i.e., function application) should be wrapped in parens, since it might be substituted in a place where parens were implicit before (like `f(x)` becoming `x + 3`). The problem is NOT that whatever is being substituted into the body of a lambda should have parens wrapped around it, since that wouldn't fix the problem in these examples.

It might still be worth implementing the latter idea, but so far I couldn't find any examples where it becomes a problem — maybe this is because what gets substituted is a `Span`, so it's like there are implicit parens around the expression that phosphorus understands in the parse tree.

**Comment by EasyArray** [comment]
The latter *is* actually an issue. It doesn't often arise, because the arguments to the &lambda;-function are generally evaluated first, simulating parentheses. However, when the argument is something that remains unevaluated in phosphorus (&phi; type: `code`), this issue can arise. For instance:
```
[λf . [λn . f == n]](foo(x) & bar(y))
```
evaluates to
```
[λn∈e. foo(x) ∧ bar(y) == 1]
```

**Comment by havijw** [comment]
Thanks for the example, that's exactly what I was trying to find! I'm adding this in the same branch.
